name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**/*.md"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@4f5aa3e38c781f1b01e78fb9255527cee8a6efa6 # v1.8.0
        with:
          node-version: "24"
          cache: true

      - name: Install dependencies
        run: vp install

      - name: Check code
        run: vp check

      - name: Build project
        run: vp build
